# Generated by Django 5.0.4 on 2024-04-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0007_remove_studentrating_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
