# Generated by Django 5.0.4 on 2024-04-28 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0008_alter_studentrating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='complite_by',
            field=models.ManyToManyField(blank=True, related_name='completed_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
