# Generated by Django 5.0.4 on 2024-04-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0010_rename_complite_by_lesson_complete_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='complete_by',
        ),
    ]
