# Generated by Django 5.0.4 on 2024-04-28 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0012_remove_course_students_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
