# Generated by Django 5.0.4 on 2024-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoursesApp', '0013_course_students_delete_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
